### ISSUE TITLE
Hidden files are still being shown?

### ISSUE THREAD

**Issue by vesper8** [oneduo/nova-file-manager#87] opened 2022-09-27 10:17 UTC
Using 0.7.0

In my config file I see that the default is to not show hidden file

`'show_hidden_files' => env('NOVA_FILE_MANAGER_SHOW_HIDDEN_FILES', false),`

And yet in some folders I am seeing the `.DS_Store`, shouldn't this file be hidden?

**Comment by crezra** [comment] 2022-09-27 10:30
Hi

Unable to reproduce this, please check your config (or cached config eventually) or please provide more details about the issue.

<img width="380" alt="CleanShot 2022-09-27 at 12 29 33@2x" src="https://user-images.githubusercontent.com/81156495/192502692-54a0c788-4a10-4547-ab3c-78e19e4a36b0.png">

**Comment by crezra** [comment] 2022-09-27 18:27
closing this as unable to reproduce

**Closed by crezra** 2022-09-27 18:27 UTC
Labels: Needs information
