### ISSUE TITLE
Search does not function properly

### ISSUE THREAD

**Issue by miagg** [oneduo/nova-file-manager#126] opened 2023-01-24 17:58 UTC
When searching for a filename I get a list of found files like the following image

![1](https://user-images.githubusercontent.com/6439071/214369998-6f282d7a-3742-485b-97a1-481eec83ec7b.png)

However when I click on an item, nothing happens 🤷‍♂️

If I am on a folder with only a few images (not paginated) then searching and clicking on a result would open the image modal but without a "Select Image" action! 

**To Reproduce**

1. Click on FileManager field: "Choose Image"
2. Click on "Search"
3. Search for an item on a folder containing a lot of images (paginated)
4. Click on a result
5. See Error

**Expected behavior**
Ideally, I want to automatically select the image and return back to the resource but I feel it should better open the image modal with all actions (crop,delete, etc.) with a "Select Image" action.

**Screenshots**
Posted above

**Desktop (please complete the following information):**

- OS: Mac OS Monterey 13.1
- Browser Chrome
- Version 109

**Smartphone (please complete the following information):**
Not Applicable

**Additional context**
Not Applicable

**Comment by mikaelpopowicz** [comment] 2023-01-24 22:18
Hi @miagg 

Do you have any errors in you browser console ?

**Comment by miagg** [comment] 2023-01-25 06:08
Hi @mikaelpopowicz,
No there are no errors at all, which is strange. Is this normal behavior? Shouldn't a modal popup in order to select the image?

Here is a video demonstration. 

https://user-images.githubusercontent.com/6439071/214492546-53b350f1-7c59-4ae8-912f-8e0ff8a5cb4a.mov

**Comment by Rezrazi** [comment] 2023-01-25 10:37
A preview modal should open indeed, investigating this. We should get back to you very soon once we determine the cause of this

**Comment by mikaelpopowicz** [comment] 2023-01-25 11:39
Hi @miagg 

I'm not able to reproduce your issue


https://user-images.githubusercontent.com/5689944/214553973-b2487ff9-62cf-44c6-b455-7526219eb55a.mp4

Do you mind providing us a public repository where we might be able to reproduce this issue ?

Thank you

**Comment by miagg** [comment] 2023-01-25 11:42
> Hi @miagg
> 
> I'm not able to reproduce your issue
> 
>  CleanShot.2023-01-25.at.12.32.19.mp4 
> 
> Do you mind providing us a public repository where we might be able to reproduce this issue ?
> 
> Thank you

You need to have more images and search for an image on another page

**Comment by Rezrazi** [comment] 2023-01-27 19:46
We're unable to reproduce
Please provide a minimal setup in a public repo with the package to help us better understand the issue and potentially fix it

**Comment by miagg** [comment] 2023-01-27 20:11
As I said, the problem arrises from pagination. 

Here is a demo repo
https://github.com/miagg/nova

And if you want to test it out live (for the next 3 hours) here is a live url
https://5f45-2-87-144-165.eu.ngrok.io/nova

user: demo@demo.com
pass: demo

Try to search for an item not in first page (term: `ios`)

**Comment by mikaelpopowicz** [comment] 2023-01-27 23:04
Hi @miagg 

This is fixed in v0.8.0.

**Closed by mikaelpopowicz** 2023-01-27 23:04 UTC
Labels: invalid, Needs information
